## Name: Thiago de Oliveira da Costa - StId: 2020005
### GitHub:  https://github.com/ThBrasilDaCosta/ML-Firewall-Inc-Traffic

### Project: Machine Learning Firewall Incoming Traffic.

##### Importing necessary labraries:

In [1]:
import pandas as pd
import numpy as np

##### Loading CSV file:

In [2]:
firewall_traffic = pd.read_csv('log2.csv')

##### Data Understanding:

In [3]:
firewall_traffic.shape

(65532, 12)

In [4]:
firewall_traffic.head(10)

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0        57222                53            54587                    53   
1        56258              3389            56258                  3389   
2         6881             50321            43265                 50321   
3        50553              3389            50553                  3389   
4        50002               443            45848                   443   
5        51465               443            39975                   443   
6        60513             47094            45469                 47094   
7        50049               443            21285                   443   
8        52244             58774             2211                 58774   
9        50627               443            16215                   443   

   Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  pkts_sent  \
0    177          94              83        2                  30          1   
1   4768        1600            3168       19                  17         10   
2    238         118             120        2                1199          1   
3   3327        1438            1889       15                  17          8   
4  25358        6778           18580       31                  16         13   
5   3961        1595            2366       21                  16         12   
6    320         140             180        6                   7          3   
7   7912        3269            4643       23                  96         12   
8     70          70               0        1                   5          1   
9   8256        1674            6582       31                  75         15   

   pkts_received Action  
0              1  allow  
1              9  allow  
2              1  allow  
3              7  allow  
4             18  allow  
5              9  allow  
6              3  allow  
7             11  allow  
8              0  allow  
9             16  allow

In [5]:
firewall_traffic.dtypes

Source Port              int64
Destination Port         int64
NAT Source Port          int64
NAT Destination Port     int64
Bytes                    int64
Bytes Sent               int64
Bytes Received           int64
Packets                  int64
Elapsed Time (sec)       int64
pkts_sent                int64
pkts_received            int64
Action                  object
dtype: object

In [6]:
firewall_traffic.describe()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
count  65532.000000      65532.000000     65532.000000          65532.000000   
mean   49391.969343      10577.385812     19282.972761           2671.049930   
std    15255.712537      18466.027039     21970.689669           9739.162278   
min        0.000000          0.000000         0.000000              0.000000   
25%    49183.000000         80.000000         0.000000              0.000000   
50%    53776.500000        445.000000      8820.500000             53.000000   
75%    58638.000000      15000.000000     38366.250000            443.000000   
max    65534.000000      65535.000000     65535.000000          65535.000000   

              Bytes    Bytes Sent  Bytes Received       Packets  \
count  6.553200e+04  6.553200e+04    6.553200e+04  6.553200e+04   
mean   9.712395e+04  2.238580e+04    7.473815e+04  1.028660e+02   
std    5.618439e+06  3.828139e+06    2.463208e+06  5.133002e+03   
min    6.000000e+01  6.000000e+01    0.000000e+00  1.000000e+00   
25%    6.600000e+01  6.600000e+01    0.000000e+00  1.000000e+00   
50%    1.680000e+02  9.000000e+01    7.900000e+01  2.000000e+00   
75%    7.522500e+02  2.100000e+02    4.490000e+02  6.000000e+00   
max    1.269359e+09  9.484772e+08    3.208818e+08  1.036116e+06   

       Elapsed Time (sec)      pkts_sent  pkts_received  
count        65532.000000   65532.000000   65532.000000  
mean            65.833577      41.399530      61.466505  
std            302.461762    3218.871288    2223.332271  
min              0.000000       1.000000       0.000000  
25%              0.000000       1.000000       0.000000  
50%             15.000000       1.000000       1.000000  
75%             30.000000       3.000000       2.000000  
max          10824.000000  747520.000000  327208.000000

In [7]:
firewall_traffic.isna().sum()

Source Port             0
Destination Port        0
NAT Source Port         0
NAT Destination Port    0
Bytes                   0
Bytes Sent              0
Bytes Received          0
Packets                 0
Elapsed Time (sec)      0
pkts_sent               0
pkts_received           0
Action                  0
dtype: int64

In [8]:
firewall_traffic.loc[firewall_traffic.duplicated()]

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
268          21268             62609                0                     0   
351          48706             23393                0                     0   
593          65003             57470                0                     0   
632            443             49988                0                     0   
661          10669             49756                0                     0   
...            ...               ...              ...                   ...   
65517        54874               445                0                     0   
65519        49784               445                0                     0   
65521        42995             26467                0                     0   
65522        53314             64097                0                     0   
65531        54867               445                0                     0   

       Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
268      146         146               0        1                   0   
351       60          60               0        1                   0   
593       78          78               0        1                   0   
632       82          82               0        1                   0   
661       60          60               0        1                   0   
...      ...         ...             ...      ...                 ...   
65517     70          70               0        1                   0   
65519     70          70               0        1                   0   
65521     62          62               0        1                   0   
65522     66          66               0        1                   0   
65531     70          70               0        1                   0   

       pkts_sent  pkts_received Action  
268            1              0   deny  
351            1              0   deny  
593            1              0   deny  
632            1              0   deny  
661            1              0   deny  
...          ...            ...    ...  
65517          1              0   drop  
65519          1              0   drop  
65521          1              0   deny  
65522          1              0   deny  
65531          1              0   drop  

[8362 rows x 12 columns]

In [9]:
firewall_traffic.columns

Index(['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received',
       'Action'],
      dtype='object')

##### Data cleaning:

In [10]:
firewall_traffic = firewall_traffic.loc[~firewall_traffic.duplicated(subset=['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received',
       'Action'])].reset_index(drop=True).copy()

In [11]:
firewall_traffic

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0            57222                53            54587                    53   
1            56258              3389            56258                  3389   
2             6881             50321            43265                 50321   
3            50553              3389            50553                  3389   
4            50002               443            45848                   443   
...            ...               ...              ...                   ...   
57165        51710             43069            65147                 43069   
57166        63691                80            13237                    80   
57167        50964                80            13485                    80   
57168        54871               445                0                     0   
57169        54870               445                0                     0   

         Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0          177          94              83        2                  30   
1         4768        1600            3168       19                  17   
2          238         118             120        2                1199   
3         3327        1438            1889       15                  17   
4        25358        6778           18580       31                  16   
...        ...         ...             ...      ...                 ...   
57165       70          70               0        2                   8   
57166      314         192             122        6                  15   
57167  4680740       67312         4613428     4675                  77   
57168       70          70               0        1                   0   
57169       70          70               0        1                   0   

       pkts_sent  pkts_received Action  
0              1              1  allow  
1             10              9  allow  
2              1              1  allow  
3              8              7  allow  
4             13             18  allow  
...          ...            ...    ...  
57165          2              0  allow  
57166          4              2  allow  
57167        985           3690  allow  
57168          1              0   drop  
57169          1              0   drop  

[57170 rows x 12 columns]

In [12]:
firewall_traffic.shape

(57170, 12)

In [13]:
firewall_traffic.describe()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
count  57170.000000      57170.000000     57170.000000          57170.000000   
mean   50532.499738       8052.147035     22048.739549           3054.123491   
std    13880.680957      16513.145167     22141.986286          10363.545911   
min        0.000000          0.000000         0.000000              0.000000   
25%    49450.000000         53.000000         0.000000              0.000000   
50%    54013.000000        443.000000     16362.500000             53.000000   
75%    58574.000000        445.000000     41883.750000            443.000000   
max    65534.000000      65535.000000     65535.000000          65535.000000   

              Bytes    Bytes Sent  Bytes Received       Packets  \
count  5.717000e+04  5.717000e+04    5.717000e+04  5.717000e+04   
mean   1.113147e+05  2.564701e+04    8.566766e+04  1.177065e+02   
std    6.015189e+06  4.098545e+06    2.637029e+06  5.495436e+03   
min    6.000000e+01  6.000000e+01    0.000000e+00  1.000000e+00   
25%    7.000000e+01  7.000000e+01    0.000000e+00  1.000000e+00   
50%    1.930000e+02  9.400000e+01    9.000000e+01  2.000000e+00   
75%    1.139000e+03  5.080000e+02    6.690000e+02  1.000000e+01   
max    1.269359e+09  9.484772e+08    3.208818e+08  1.036116e+06   

       Elapsed Time (sec)      pkts_sent  pkts_received  
count        57170.000000   57170.000000   57170.000000  
mean            75.116547      47.279255      70.427200  
std            322.519323    3446.210063    2380.254144  
min              0.000000       1.000000       0.000000  
25%              0.000000       1.000000       0.000000  
50%             26.000000       1.000000       1.000000  
75%             31.000000       5.000000       4.000000  
max          10824.000000  747520.000000  327208.000000

In [14]:
firewall_traffic['Action'].unique()

array(['allow', 'drop', 'deny', 'reset-both'], dtype=object)

##### Applying encoding method:

In [15]:
firewall_traffic['Action'].unique()

array(['allow', 'drop', 'deny', 'reset-both'], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [17]:
firewall_traffic = firewall_traffic
firewall_traffic.Action = le.fit_transform(firewall_traffic.Action)
firewall_traffic

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0            57222                53            54587                    53   
1            56258              3389            56258                  3389   
2             6881             50321            43265                 50321   
3            50553              3389            50553                  3389   
4            50002               443            45848                   443   
...            ...               ...              ...                   ...   
57165        51710             43069            65147                 43069   
57166        63691                80            13237                    80   
57167        50964                80            13485                    80   
57168        54871               445                0                     0   
57169        54870               445                0                     0   

         Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0          177          94              83        2                  30   
1         4768        1600            3168       19                  17   
2          238         118             120        2                1199   
3         3327        1438            1889       15                  17   
4        25358        6778           18580       31                  16   
...        ...         ...             ...      ...                 ...   
57165       70          70               0        2                   8   
57166      314         192             122        6                  15   
57167  4680740       67312         4613428     4675                  77   
57168       70          70               0        1                   0   
57169       70          70               0        1                   0   

       pkts_sent  pkts_received  Action  
0              1              1       0  
1             10              9       0  
2              1              1       0  
3              8              7       0  
4             13             18       0  
...          ...            ...     ...  
57165          2              0       0  
57166          4              2       0  
57167        985           3690       0  
57168          1              0       2  
57169          1              0       2  

[57170 rows x 12 columns]

In [18]:
#from sklearn.preprocessing import OneHotEncoder
#ohe = OneHotEncoder(sparse=False)
#ohetransform = ohe.fit_transform(firewall_traffic[['Action']])

In [19]:
#ohetransform = pd.DataFrame(ohetransform, columns=ohe.categories_[0])

In [20]:
#ohetransform

In [21]:
#firewall_traffic = pd.concat([firewall_traffic, ohetransform], axis=1).drop(columns = ['Action'])

In [22]:
firewall_traffic.head()

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0        57222                53            54587                    53   
1        56258              3389            56258                  3389   
2         6881             50321            43265                 50321   
3        50553              3389            50553                  3389   
4        50002               443            45848                   443   

   Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  pkts_sent  \
0    177          94              83        2                  30          1   
1   4768        1600            3168       19                  17         10   
2    238         118             120        2                1199          1   
3   3327        1438            1889       15                  17          8   
4  25358        6778           18580       31                  16         13   

   pkts_received  Action  
0              1       0  
1              9       0  
2              1       0  
3              7       0  
4             18       0

In [26]:
firewall_traffic.tail(15)

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
57155        58574               443             3429                   443   
57156        56985                53            45052                    53   
57157        50269               445                0                     0   
57158        50270               445                0                     0   
57159        50268               445                0                     0   
57160        54013             37965                0                     0   
57161        49783               445                0                     0   
57162        55142             26467                0                     0   
57163        53848             36237                0                     0   
57164        65323                53            33275                    53   
57165        51710             43069            65147                 43069   
57166        63691                80            13237                    80   
57167        50964                80            13485                    80   
57168        54871               445                0                     0   
57169        54870               445                0                     0   

         Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
57155     3447         788            2659       13                 135   
57156      711          87             624        2                  31   
57157       66          66               0        1                   0   
57158       66          66               0        1                   0   
57159       66          66               0        1                   0   
57160       66          66               0        1                   0   
57161       70          70               0        1                   0   
57162       66          66               0        1                   0   
57163       62          62               0        1                   0   
57164      356         118             238        2                  30   
57165       70          70               0        2                   8   
57166      314         192             122        6                  15   
57167  4680740       67312         4613428     4675                  77   
57168       70          70               0        1                   0   
57169       70          70               0        1                   0   

       pkts_sent  pkts_received  Action  
57155          6              7       0  
57156          1              1       0  
57157          1              0       2  
57158          1              0       2  
57159          1              0       2  
57160          1              0       1  
57161          1              0       2  
57162          1              0       1  
57163          1              0       1  
57164          1              1       0  
57165          2              0       0  
57166          4              2       0  
57167        985           3690       0  
57168          1              0       2  
57169          1              0       2

In [24]:
firewall_traffic.columns

Index(['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received',
       'Action'],
      dtype='object')

##### Decision Tree ML model:

In [27]:
independent_features = ['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received']

dependent_features = ['Action']

X = firewall_traffic[independent_features]
y = firewall_traffic[dependent_features]

In [28]:
print(X)

       Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0            57222                53            54587                    53   
1            56258              3389            56258                  3389   
2             6881             50321            43265                 50321   
3            50553              3389            50553                  3389   
4            50002               443            45848                   443   
...            ...               ...              ...                   ...   
57165        51710             43069            65147                 43069   
57166        63691                80            13237                    80   
57167        50964                80            13485                    80   
57168        54871               445                0                     0   
57169        54870               445                0                     0   

         Bytes  Bytes Sent  Bytes Received  Packets

In [29]:
print(y)

       Action
0           0
1           0
2           0
3           0
4           0
...       ...
57165       0
57166       0
57167       0
57168       2
57169       2

[57170 rows x 1 columns]


In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=17, test_size = 0.2)

In [32]:
X_train.shape

(45736, 11)

In [33]:
X_test.shape

(11434, 11)

In [34]:
y_train.shape

(45736, 1)

In [35]:
y_test.shape

(11434, 1)

In [36]:
from sklearn.tree import DecisionTreeClassifier

In [37]:
dtc = DecisionTreeClassifier()

In [38]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [44]:
from sklearn.metrics import confusion_matrix

In [45]:
print(confusion_matrix(y_test, y_pred))

[[7589    0    0    0]
 [   0 1532   10    6]
 [   0   10 2281    0]
 [   0    3    0    3]]


In [39]:
y_pred = dtc.predict(X_test)

In [40]:
from sklearn.metrics import classification_report

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7589
           1       0.99      0.99      0.99      1548
           2       1.00      1.00      1.00      2291
           3       0.33      0.50      0.40         6

    accuracy                           1.00     11434
   macro avg       0.83      0.87      0.85     11434
weighted avg       1.00      1.00      1.00     11434



In [42]:
dtc.feature_importances_

array([3.00186191e-03, 3.29142124e-01, 2.54089512e-04, 2.22670913e-04,
       1.81279720e-04, 3.33078229e-04, 0.00000000e+00, 1.25854445e-02,
       6.53869030e-01, 0.00000000e+00, 4.10420680e-04])

In [46]:
X.columns

Index(['Source Port', 'Destination Port', 'NAT Source Port',
       'NAT Destination Port', 'Bytes', 'Bytes Sent', 'Bytes Received',
       'Packets', 'Elapsed Time (sec)', 'pkts_sent', 'pkts_received'],
      dtype='object')

In [47]:
features = pd.DataFrame(dtc.feature_importances_, index = X.columns)

In [48]:
features

0
Source Port           0.003002
Destination Port      0.329142
NAT Source Port       0.000254
NAT Destination Port  0.000223
Bytes                 0.000181
Bytes Sent            0.000333
Bytes Received        0.000000
Packets               0.012585
Elapsed Time (sec)    0.653869
pkts_sent             0.000000
pkts_received         0.000410